[project]
name = "health-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "openai>=1.97.0",
    "openai-agents>=0.2.2",
    "pymupdf>=1.26.3",
    "streamlit>=1.47.0",
]
